### ISSUE TITLE
ES2018 부터 추가된 기능 파악

### ISSUE THREAD

**Issue by jiwonkirn** [helloworld-javascript/hwjs-book#10]
@seungha-kim @sehyunchung @shiincs

Outdated 내용 개선 과제 리스팅 및 히스토리를 관리를 위해 이슈 생성했습니다.

개선 및 추가해야할 내용들 해당 이슈 수정해서 추가해주시거나 코멘트로 달아주시면 좋을 것 같습니다. :)

### 등록된 이슈 체크

- ES2018 Rest/Spread Properties - #14
- ES2018 for await...of(async-iteration) - #33
- ES2018 Promise.prototype.finally - #23
- ES2019 Array.prototype.flat[Map] - #34
- ES2019 String.prototype.trim[Start, End] - #27
- ES2019 Optional Catch bind - #35
- ES2019 Object.fromEntries - #36
- ES2020 Optional chaining - #29
- ES2020 Nullish coalescing operator - #28 
- ES2020 Promise.allSettled - #30
- ES2020 BigInt - #32
- ES2020 dynamic import - #31
- ES2021 String.prototype.replaceAll - #37
- ES2021 Logical assignment operators - #38
- ES2021 Promise.prototype.any - #39
- ES2021 Numeric separator - #40

**Comment by jiwonkirn** [comment]
ES2019, ES2020, ES2021 내용 중 주요 스펙 리스팅해봤습니다.

- [Optional chaining](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
- [Nullish coalescing operator](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)
- [Array.prototype.flat[Map]](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/flat)
- [Optional Catch bind](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/try...catch)
- [Promise.allSettled](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled)
- [BigInt](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/BigInt)
- [String.prototype.replaceAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)
- Logical assignment operators
  - [OR](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment)
  - [AND](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment)

나머지 누락된 확정 스펙들은 해당 [TC39 링크](https://github.com/tc39/proposals/blob/master/finished-proposals.md)에서 확인하실 수 있습니다.

**Comment by sehyunchung** [comment]
지원님 리스팅 해주신 각 스펙들에 해당되는 기존 챕터들 찾아보았습니다.

> * [Optional chaining](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
> * [Nullish coalescing operator](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)
> * Logical assignment operators
>   * [OR](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment)
>   * [AND](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment)

[3.5 연산자 더 알아보기](https://helloworldjavascript.net/pages/245-operator-in-depth.html) 에 추가

> * [Array.prototype.flat[Map]](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/flat)

[2.9 배열](https://helloworldjavascript.net/pages/190-array.html)

> * [Optional Catch bind](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/try...catch)

[4.5 예외처리](https://helloworldjavascript.net/pages/290-exception.html)

> * [Promise.allSettled](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled)

[4.4 비동기 프로그래밍](https://helloworldjavascript.net/pages/285-async.html)

> * [BigInt](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/BigInt)

[2.2 number 타입](https://helloworldjavascript.net/pages/130-number.html)

> * [String.prototype.replaceAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)

[2.3 string 타입](https://helloworldjavascript.net/pages/140-string.html)

**Comment by seungha-kim** [comment]
@jiwonkirn @sehyunchung 교재에 ES2018 내용도 안들어가 있어서, 조사 범위를 ES2018 범위로 늘려주시면 좋을 것 같습니다!

**Comment by jiwonkirn** [comment]
@seungha-kim @sehyunchung 
아래 4개 리스트에 추가했습니다. 

- [for await...of(async-iteration)](https://webcache.googleusercontent.com/search?q=cache:CA1lly9lsX4J:https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/for-await...of+&cd=1&hl=ko&ct=clnk&gl=kr)
- [String.prototype.trim[Start, End]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart)
- [dynamic import](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/import)
- [Promise.prototype.finally](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

ES2018중에 object rest/spread operator는 포함되어있었습니다. ㅎㅎ
권한이 없는지 세현님 글을 수정하지는 못하는군요. ㅠㅠ

**Comment by seungha-kim** [comment]
ES2018 이후로 추가된 기능 파악은 어느정도 됐다고 생각돼서, 이제 작업을 잘게 쪼개서 각각을 이슈로 등록하고 위 이슈는 닫는게 좋을 것 같습니다. 예시로 #23 이슈를 만들어두었으니, 시간되시는 분들께서 이슈 생성해주세요! 모든 이슈가 생성되었다고 판단이 되면 @jiwonkirn 님이 본 이슈 닫아주시면 될 것 같습니다 ㅎㅎ

**Comment by seungha-kim** [comment]
ES2021에 추가된 내용 중

- [Promise.prototype.any](https://github.com/tc39/proposal-promise-any)
- [Numeric separator](https://github.com/tc39/proposal-numeric-separator)

요것도 어렵지 않게 교재에 넣을 수 있을 것 같습니다.

**Comment by seungha-kim** [comment]
정규표현식은 교재에 관련 내용이 없기 때문에 이번에는 패스하시죵. 정규표현식 챕터를 만들때 생각하면 될 것 같습니다. 이슈 생성해놓았습니다. #26

**Comment by jiwonkirn** [comment]
@seungha-kim @sehyunchung @shiincs
넵 코멘트 확인했습니다. :) 
일단 본 [이슈](https://github.com/helloworld-javascript/hwjs-book/issues/10#issue-763199177)에 리스팅된 것들은 승하님께서 미리 작성해주신 이슈 포멧을 참고하여 모두 등록했습니다.
해당 [코멘트](https://github.com/helloworld-javascript/hwjs-book/issues/10#issuecomment-748426304) 참고하여 해당 이슈는 닫도록 하겠습니다. :)
**혹시라도 스펙중에 포함시킬만 한데 누락됐다고 생각하시는 것이 있다면 이슈로 등록 부탁드립니다!**
