### ISSUE TITLE
not found 이슈

### ISSUE THREAD

**Issue by yoonjeong-heo** [helloworld-javascript/hwjs-book#100]
https://helloworldjavascript.net/pages/160-null-undefined.html

마지막 부분 '연산자 더 알아보기' 클릭 시 not found 화면이 뜹니다
링크된 url 확장자를 html 로 바꾸니 되긴 되던데 😂

**Comment by seungha-kim** [comment]
https://github.com/helloworld-javascript/hwjs-book/commit/59d9e95ca16cf1c128b73e0a1c69c5c0faa3807b 에서 수정되었습니다. 제보 감사합니다!
