### ISSUE TITLE
내용 추가/변경할 수 있는 공간 만들고 채우는 작업

### ISSUE THREAD

**Issue by changseon-shin** [helloworld-javascript/hwjs-book#11]
이슈를 수정하시거나 코멘트로 달아주세요!

[개선 및 추가할 내용]
*

**Comment by seungha-kim** [comment]
@shiincs 앗 이 이슈도 회사계정이신 것 같은데 이 이슈도 닫을까요?

기여자 목록에도 깃헙 아이디가 changseon-shine 으로 되어있는데 shiincs 로 수정하도록 하겠습니다!

**Comment by shiincs** [comment]
앗 그러네요.. 이 이슈도 닫을게요 ㅎㅎ
수정해주셔서 감사합니다!
