### ISSUE TITLE
ES2020 Nullish coalescing operator

### ISSUE THREAD

**Issue by seungha-kim** [helloworld-javascript/hwjs-book#28]
관련 문서

- [TC39 proposal](https://github.com/tc39/proposal-nullish-coalescing)
- [MDN doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)
- [MDN doc (assignment)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment)

관련된 챕터

- 2.5 null과 undefined
- 3.5 연산자 더 알아보기

2.5 null과 undefined 에서 null check를 할 때 `==` 등호를 쓰라고 권장하고 있는데, 여기에 optional chaining과 nullish coaleacing을 쓰라는 내용을 추가해도 좋을 것 같다. 혹은 초반에 다루기가 복잡하다고 생각되면 3.5 연산자 더 알아보기에 넣거나 아예 다른 챕터를 만들어도 좋을 것 같다.

**Comment by jiwonkirn** [comment]
@seungha-kim @shiincs @sehyunchung
내용이 들어가는 위치도 중요하지만 비교적 최신 스펙인 경우에는 표시를 해줄 필요성도 있을 것 같은데요.
최신 스펙마다 주석 혹은 아이콘을 넣어야 하는 것인지... 잘못하면 다소 번잡해보일 수도 있겠습니다.  
이 부분은 논의가 필요할 것 같은데 추후 개편 예정이라면 일단은 고려하지 않는 것으로 할까요?

> 몇몇 책에서는 ES6+는 따로 설명하는 케이스가 많았던 것으로 기억합니다.

**Comment by seungha-kim** [comment]
관련 이슈가 만들어져 있네요. #17 

나중에 #17 작업을 할 때를 위해 우리끼리 포맷을 정해서 주석으로 미리 표시를 해두면 좋을 것 같습니다!
