### ISSUE TITLE
오타 제보!

### ISSUE THREAD

**Issue by mathisverydifficult** [helloworld-javascript/hwjs-book#78]
https://helloworldjavascript.net/pages/170-function.html#%EB%B3%80%EC%88%98-%EA%B0%80%EB%A6%AC%EA%B8%B0-variable-shadowing

같은 이름을 같는  -> 같은 이름을 갖는

**Comment by seungha-kim** [comment]
https://github.com/helloworld-javascript/hwjs-book/commit/3f20b3320af4e69554e2b588a0ec661490a3872b 에서 수정되었습니다. 제보 감사합니다!
