### ISSUE TITLE
Static site generator 후보 조사

### ISSUE THREAD

**Issue by seungha-kim** [helloworld-javascript/hwjs-book#8]
[Gitbook CLI 유지보수가 끊김](https://github.com/GitbookIO/gitbook#%EF%B8%8F-deprecation-warning)

요구사항

- Markdown 형식으로 컨텐츠를 작성할 수 있어야 함 (나중에는 몰라도, 일단 작업을 시작하기 위해서 최소한 이건 되어야 함)
- 책 형식만 지원하는게 아니라, 마음대로 커스터마이징 할 수 있으면 좋음

후보

- Gatsby
- Hugo
- Next.js
- Nuxt.js

**Comment by sxhx** [comment]
선택시 고려해야 할 사항들을 정리해보면 좋을 것 같아요!

**Comment by sehyunchung** [comment]
선택시 고려해야 될 것들을 정리해보면 좋을 것 같아요!

**Comment by sehyunchung** [comment]
> * Markdown 형식으로 컨텐츠를 작성할 수 있어야 함 (나중에는 몰라도, 일단 작업을 시작하기 위해서 최소한 이건 되어야 함)
> * 책 형식만 지원하는게 아니라, 마음대로 커스터마이징 할 수 있으면 좋음

여러모로 Gatsby가 제일 편할 것 같긴 하네요😃

아래는 빠르게 찾아본 문서화 관련 Gatsby template/theme/plugin 등등 입니다.
- https://primer.style/doctocat/
- https://smooth-doc.com
- https://github.com/Rocketseat/gatsby-themes/tree/master/@rocketseat/gatsby-theme-docs
- https://www.gatsbyjs.com/starters/hasura/gatsby-gitbook-starter
- https://github.com/ericwindmill/gatsby-starter-docs

**Comment by seungha-kim** [comment]
최소 요구사항 외에 있으면 좋은 것들 좀 더 생각해봤습니다.

- 블로그 붙일 수 있으면 좋음 (정규 교재에 넣기는 애매하지만 그래도 출판하고 싶은 내용이 생길 것 같아서)
- 텍스트 검색 기능 편하게 붙일 수 있으면 좋음
- (챕터 단위만이라도) 목차 자동생성 기능 있으면 좋음
- 추후 동적 컨텐츠를 만들 수 있는 구조면 좋음 (JS 코드를 직접/간접적으로 삽입하거나, MDX 등 Markdown 확장 언어를 사용할 수 있으면 좋음)

**Comment by seungha-kim** [comment]
하나 덧붙이자면 현재 작성되어 있는 .md 파일을 거의 안 고치고 SSG만 바꿔서 새 사이트 띄울 수 있으면 가장 좋습니다.

**Comment by sehyunchung** [comment]
일단 첫번째로는 https://github.com/hasura/gatsby-gitbook-starter 요것이 어떨까 합니다.

live demo: https://hasura.io/learn/graphql/react/introduction/

몇가지 장점이 있는데요,
- gitbook 이랑 생긴게 같음.
- [mdx, algolia, code live editing, pwa, dark mode등의 세팅이 이미 되어있음](https://github.com/hasura/gatsby-gitbook-starter#-features).
- [config가 간단](https://github.com/hasura/gatsby-gitbook-starter#-configure)

빠르게 시작하기 좋을 것 같습니다.

**Comment by sehyunchung** [comment]
글고 두번째로는  https://smooth-doc.com 도 편하고 좋을 것 같아요.

gitbook starter 와 같은 기능을 제공하고 역시 gatsby를 사용합니다만 자체 컴포넌트들을 추가로 제공한다는 장점이 있네요. https://smooth-doc.com/docs/components/article/

예시: https://use-gesture.netlify.app

책 보다는 개발문서 제작에 좀 더 특화된 것 같긴 합니다.

**Comment by seungha-kim** [comment]
논의

템플릿 별 단점들이 좀 있음

- TS 지원이 안되거나
- 라이브러리 버전이 낮은데 업데이트 하면 깨지거나

세현님이추가 조사 필요하다고 하심

**Comment by sehyunchung** [comment]
말씀드렸던 Github 에서 만든 template https://primer.style/doctocat/

**Comment by seungha-kim** [comment]
https://primer.style/doctocat/ 으로 땅땅땅!
