### ISSUE TITLE
연산자 오타 제보 

### ISSUE THREAD

**Issue by jungjinbeom** [helloworld-javascript/hwjs-book#87]
Optional chaining 설명 부분 
https://helloworldjavascript.net/pages/245-operator-in-depth.html
.? -> ?.

**Comment by seungha-kim** [comment]
https://github.com/helloworld-javascript/hwjs-book/commit/036b716e1076a79ed2d62be0fbeb44806f97d204 에서 수정되었습니다. 제보 감사합니다!
